name: Deploy

concurrency: production

on:
  push:
    branches:
      - main

jobs: 
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: echo "$EC2_SSH_PRIVATE_KEY" > ssh_key.pem && chmod 600 ssh_key.pem

      - name: Check variable
        run: |
          echo "private_key: $EC2_SSH_PRIVATE_KEY"
          cat ssh_key.pem
          echo "ssh_user: $EC2_USER"
          echo "ssh_host: $EC2_HOST"

      - name: SSH into EC2 and pull latest code
        run: |
          ssh -i ssh_key.pem $EC2_USER@$EC2_HOST 
          cd my-app
          git pull origin main
      - name: Clean up
        run: rm ssh_key.pem
