name: Deploy

concurrency: production

on:
  push:
    branches:
      - main

jobs: 
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check variable
        run: |
          echo "private_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}"
          echo "ssh_user: ${{ secrets.EC2_USER }}"
          echo "ssh_host: ${{ secrets.EC2_HOST }}"

      - name: Set up SSH key
        run: echo ${{ secrets.EC2_SSH_PRIVATE_KEY }} > ssh_key.pem && chmod 600 ssh_key.pem

      - name: SSH into EC2 and pull latest code
        run: |
          ssh -i ssh_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}
          cd my-app
          git pull origin main
      - name: Clean up
        run: rm ssh_key.pem
