name: Deploy

concurrency: production

on:
  push:
    branches:
      - main

jobs: 
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.EC2_HOST }}
      - name: Add remote host key to known hosts
        run: ssh-keyscan ${{ secrets.EC2_HOST }} >> /home/runner/.ssh/known_hosts
      - name: Deploy
        run: ssh -i ~/.ssh/id_rsa ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} "cd ebs-data/my-app && git pull origin main && docker-compose up -d && docker-compose run web sh -c 'bundle install && rails db:migrate'"
